### ISSUE TITLE
Add a license, please!

### ISSUE THREAD

**Issue by nerdachse** [jim-works/Recursia#2]
Hello!

Thanks for sharing your awesome adventure with us.

As there is no license file attached to this repository, it's difficult to contribute anything!

Would be great if you could clarify the terms!

Best regards,
Tom

**Comment by jim-works** [comment]
Hi Tom,

Sorry, but I'm not looking for contributions at the moment. I've just figured out the direction I want to take the game in, and would hate to scrap someone's work because of my lack of planning. Eventually, I may take contributions. I plan to sell this game though, so I'd need to work out the business side first too.

I really appreciate the interest! I will look into adding a license so people can feel more comfortable using some of my code in their own projects.

Thanks,
Jim

**Comment by nerdachse** [comment]
Hey Jim!

No worries, it's just that I am working on a similar type of game, also with quinnet, voxels (albeit leveraging the block_mesh crate, after switching from surface nets), so I figured there was an area to collaborate.

It's totally fine that you don't want that, but as is I can't really have a look at any code here and even suggest anything, because it's a legal minefield (no license means proprietary in my jurisdiction).

All the best to you! Looking forward to seeing some progress on the bevy discord!

**Comment by Brandon-Huu** [comment]
> Hi Tom,
> 
> Sorry, but I'm not looking for contributions at the moment. I've just figured out the direction I want to take the game in, and would hate to scrap someone's work because of my lack of planning. Eventually, I may take contributions. I plan to sell this game though, so I'd need to work out the business side first too.
> 
> I really appreciate the interest! I will look into adding a license so people can feel more comfortable using some of my code in their own projects.
> 
> I will reply to this issue if I decide to take contributions in the future.
> 
> Thanks, Jim

You should still a license for the project.

**Comment by jim-works** [comment]
> Hey Jim!
> 
> No worries, it's just that I am working on a similar type of game, also with quinnet, voxels (albeit leveraging the block_mesh crate, after switching from surface nets), so I figured there was an area to collaborate.
> 
> It's totally fine that you don't want that, but as is I can't really have a look at any code here and even suggest anything, because it's a legal minefield (no license means proprietary in my jurisdiction).
> 
> All the best to you! Looking forward to seeing some progress on the bevy discord!

Just added a license (GPLv3). I'm not an expert in the legal side of things, so I may have to change it for future versions. I do like the idea of keeping it this way though...

Also, I'd love to see what you're working on! It's always fun to see other voxel projects.
